package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pyfaidx >=0.7.2
    - pandas >=1.3.5
    - easyterm >=1.0.0
    - numpy >=1.17.0

about:
  home: "https://github.com/marco-mariotti/{{ name }}"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Description of project"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - marco-mariotti
